// <auto-generated />
namespace RS181977_TB181979_desafío01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Col_Tipo_CuentaBancaria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Col_Tipo_CuentaBancaria));
        
        string IMigrationMetadata.Id
        {
            get { return "202109180623015_Col_Tipo_CuentaBancaria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
